-- MySQL Script generated by MySQL Workbench
-- Tue May 29 19:04:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Runlife_sql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Runlife_sql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Runlife_sql` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Runlife_sql` ;

-- -----------------------------------------------------
-- Table `Runlife_sql`.`performances(course)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Runlife_sql`.`performances(course)` (
  `id_course` INT NOT NULL AUTO_INCREMENT,
  `distance(m)` INT NOT NULL,
  `temps(min)` INT NOT NULL,
  `calories(cal)` INT NOT NULL,
  PRIMARY KEY (`id_course`));


-- -----------------------------------------------------
-- Table `Runlife_sql`.`fav_gym`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Runlife_sql`.`fav_gym` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fav_gym` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Runlife_sql`.`fiche_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Runlife_sql`.`fiche_user` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `sexe` VARCHAR(1) NOT NULL,
  `nom de compte` BINARY(30) NOT NULL,
  `mot_de_passe` BINARY(30) NOT NULL,
  `age` INT(3) UNSIGNED ZEROFILL NOT NULL,
  `poids(kg)` INT NOT NULL,
  `taille(m)` INT NOT NULL,
  `niveau` ENUM('faible', 'moyen', 'fort') NULL,
  `performances(course)_id_course` INT NOT NULL,
  `fav_gym_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_fiche_user_performances(course)`
    FOREIGN KEY (`performances(course)_id_course`)
    REFERENCES `Runlife_sql`.`performances(course)` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fiche_user_fav_gym1`
    FOREIGN KEY (`fav_gym_id`)
    REFERENCES `Runlife_sql`.`fav_gym` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = Default
ROW_FORMAT = Dynamic;

CREATE INDEX `fk_fiche_user_performances(course)_idx` ON `Runlife_sql`.`fiche_user` (`performances(course)_id_course` ASC);

CREATE INDEX `fk_fiche_user_fav_gym1_idx` ON `Runlife_sql`.`fiche_user` (`fav_gym_id` ASC);


-- -----------------------------------------------------
-- Table `Runlife_sql`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Runlife_sql`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
